gcc_version:
  - 15.2.0
  - 14.3.0
# We don't have gcc 13.4.0 built.
#  - 13.4.0
libgfortran_soname:
  - 5
binutils_version:
  - 2.44
cross_target_platform:
  - linux-64       # [linux and x86_64]
  - linux-aarch64  # [linux and aarch64]
  - win-64         # [win]
triplet:
  - x86_64-conda-linux-gnu   # [linux and x86_64]
  - aarch64-conda-linux-gnu  # [linux and aarch64]
  - x86_64-w64-mingw32       # [win]
c_stdlib:          # [win]
  - m2w64-sysroot  # [win]
c_stdlib_version:  # [win]
  - 12             # [win]
cross_stdlib:
  - sysroot        # [linux]
  - m2w64-sysroot  # [win]
cross_stdlib_version:
  - 2.28  # [linux]
  - 12    # [win]

clang_version:
# We don't have clang 21.1 built yet.
#  - 21.1
  - 20.1
  - 19.1

FINAL_CPPFLAGS:
  - -DNDEBUG -D_FORTIFY_SOURCE=2 -O2

FINAL_CFLAGS_linux_64:
  - -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
FINAL_CFLAGS_linux_ppc64le:
  - -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_CFLAGS_linux_aarch64:
  - -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_CFLAGS_linux_s390x:
  - -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_CFLAGS_win_64:
  - -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe

FINAL_CXXFLAGS_linux_64:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
FINAL_CXXFLAGS_linux_ppc64le:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_CXXFLAGS_linux_aarch64:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_CXXFLAGS_linux_s390x:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_CXXFLAGS_win_64:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe

FINAL_FFLAGS_linux_64:
  - -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe
FINAL_FFLAGS_linux_ppc64le:
  - -fopenmp -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_FFLAGS_linux_aarch64:
  - -fopenmp -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_FFLAGS_linux_s390x:
  - -fopenmp -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
FINAL_FFLAGS_win_64:
  - -fopenmp -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe

FINAL_LDFLAGS_linux_64:
  - -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections
FINAL_LDFLAGS_linux_ppc64le:
  - -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
FINAL_LDFLAGS_linux_aarch64:
  - -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
FINAL_LDFLAGS_linux_s390x:
  - -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
FINAL_LDFLAGS_win_64:
  - -Wl,-O2 -Wl,--sort-common

FINAL_DEBUG_CPPFLAGS:
  - -D_DEBUG -D_FORTIFY_SOURCE=2 -Og

FINAL_DEBUG_CFLAGS_linux_64:
  - -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe
FINAL_DEBUG_CFLAGS_linux_ppc64le:
  - -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_CFLAGS_linux_aarch64:
  - -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_CFLAGS_linux_s390x:
  - -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_CFLAGS_win_64:
  - -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe

FINAL_DEBUG_CXXFLAGS_linux_64:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe
FINAL_DEBUG_CXXFLAGS_linux_ppc64le:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_CXXFLAGS_linux_aarch64:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_CXXFLAGS_linux_s390x:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
FINAL_DEBUG_CXXFLAGS_win_64:
  - -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe

FINAL_DEBUG_FFLAGS_linux_64:
  - -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
FINAL_DEBUG_FFLAGS_linux_ppc64le:
  - -fopenmp -mcpu=power8 -mtune=power8 -ftree-vectorize -fPIC -fstack-protector-strong -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fvar-tracking-assignments -pipe
FINAL_DEBUG_FFLAGS_linux_aarch64:
  - -fopenmp -ftree-vectorize -fPIC -fstack-protector-strong -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fvar-tracking-assignments -pipe
FINAL_DEBUG_FFLAGS_linux_s390x:
  - -fopenmp -ftree-vectorize -fPIC -fstack-protector-strong -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fvar-tracking-assignments -pipe
FINAL_DEBUG_FFLAGS_win_64:
  - -fopenmp -ftree-vectorize -fPIC -fstack-protector-strong -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fvar-tracking-assignments -pipe

FINAL_CONDA_PYTHON_SYSCONFIGDATA_NAME_linux_64:
  - _sysconfigdata_x86_64_conda_linux_gnu
FINAL_CONDA_PYTHON_SYSCONFIGDATA_NAME_linux_ppc64le:
  - _sysconfigdata_powerpc64le_conda_linux_gnu
FINAL_CONDA_PYTHON_SYSCONFIGDATA_NAME_linux_aarch64:
  - _sysconfigdata_aarch64_conda_linux_gnu
FINAL_CONDA_PYTHON_SYSCONFIGDATA_NAME_linux_s390x:
  - _sysconfigdata_s390x_conda_linux_gnu
